name: calc-push

# контролирует, когда начнется выполнение
on:
  # вызывает workflow на пуше или пуле только для главной ветки
  push:
    branches: [ master ]

  workflow_dispatch:

jobs: 
# прогон тестов
  test:
    runs-on: ubuntu-latest
    steps:
    # проверка на наличие
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Check out calc tests
        run: python test_calc.py
      
  # построение
  build:
    runs-on: ubuntu-latest
    steps:
      # проверка на наличие
      - uses: actions/checkout@v2
      # переводим в байтовый код
      - name: compile to bytecode
        run: python -m py_compile calc.py > calc.pyc
      # устанавливаем pyinstaller
      - name: setup compiler
        run: pip install pyinstaller
        # компилирование
      - name: compile to package
        run: pyinstaller calc.py  --noconfirm --onefile --console
        # устанавливаем имена
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" 
      # добавляем в отслеживание файлы и пушим их
      - name: Commit files
        run: |
            git add calc.pyc
            git add cd/calc
            git add builded/calc/calc.pkg
            git commit -a -m 'Зushed by GitHub Actions'
            git push origin main
